definitions:
  models.DoctorData:
    properties:
      _id:
        type: string
      ClinicAddress:
        type: string
      ContactNumber:
        type: integer
      Description:
        type: string
      Docter_Code:
        type: string
      Email:
        type: string
      ImageURL:
        type: string
      IsVerified:
        type: boolean
      Name:
        type: string
      Specialization:
        type: string
    type: object
  models.Homeremedies:
    properties:
      author:
        type: string
      body:
        type: string
      category:
        type: string
      content:
        type: string
      date:
        type: string
      id:
        type: integer
      image:
        type: string
      title:
        type: string
    type: object
  models.NMK:
    properties:
      _id:
        type: string
      Address:
        type: string
      Contact_Number:
        type: integer
      District:
        type: string
      Email:
        type: string
      Established_Year:
        type: integer
      ImageURL:
        type: string
      IsVerified:
        type: boolean
      NMK_Code:
        type: string
      NMK_Image:
        type: string
      NMK_Verification_Image:
        type: string
      Name:
        type: string
      Owner_Name:
        type: string
      Pincode:
        type: integer
      State:
        type: string
    type: object
  models.User:
    properties:
      _id:
        type: string
      Addiction_Duration:
        type: integer
      Addiction_Type:
        type: string
      Age:
        type: integer
      Counselling_Count:
        type: integer
      Counsellor_Name:
        type: string
      District:
        type: string
      Duration_of-Treatment:
        type: integer
      Employment_Status:
        type: integer
      Gender:
        type: string
      Guardian_Name:
        type: string
      Is_Treatment_Completed:
        type: boolean
      Joining_Date:
        type: string
      Name:
        type: string
      Nasha_Mukti_Centre_Address:
        type: string
      Nasha_Mukti_Centre_Code:
        type: string
      Nasha_Mukti_Centre_Name:
        type: string
      State:
        type: string
      Under_Treatment:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /Homeremedies:
    get:
      consumes:
      - application/json
      description: Get all Homeremedies details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Homeremedies'
      summary: Get all Homeremedies details
      tags:
      - Homeremedies
  /NMK:
    get:
      consumes:
      - application/json
      description: Get all NMK codes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NMK'
      summary: Get all NMK codes
      tags:
      - NMK
  /doctors:
    get:
      consumes:
      - application/json
      description: Get all doctors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DoctorData'
      summary: Get all doctors
      tags:
      - Doctors
  /users:
    get:
      consumes:
      - application/json
      description: Get users based on query parameters
      parameters:
      - description: Addiction Type
        in: query
        name: Addiction_Type
        type: string
      - description: Nasha Mukti Centre Code
        in: query
        name: Nasha_Mukti_Centre_Code
        type: string
      - description: Employment Status
        in: query
        name: Employment_Status
        type: integer
      - description: Is Treatment Completed
        in: query
        name: Is_Treatment_Completed
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get users
      tags:
      - User
swagger: "2.0"
